
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    Combined SIL module
    module openconfig-platform-transceiver
    revision 2018-05-15
    namespace http://openconfig.net/yang/platform/transceiver
    organization OpenConfig working group

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_cb.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "status.h"
#include "openconfig-platform-transceiver.h"

/* module static variables */
static ncx_module_t *openconfig_platform_transceiver_mod;
static obj_template_t *transceiver_obj;
static val_value_t *transceiver_val;

extern struct smiclient_globals *azg;

/* put your static variables here */

/********************************************************************
* FUNCTION y_openconfig_platform_transceiver_init_static_vars
* 
* initialize module static variables
* 
********************************************************************/
static void y_openconfig_platform_transceiver_init_static_vars (void)
{
    openconfig_platform_transceiver_mod = NULL;
    transceiver_obj = NULL;
    transceiver_val = NULL;

    /* init your static variables here */

} /* y_openconfig_platform_transceiver_init_static_vars */


static status_t
openconfig_platform_transceiver_config_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;

    val_value_t* name_val = 0;
    val_value_t* en_val = 0;

    switch (cbtyp) {

    case AGT_CB_APPLY:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
        case OP_EDITOP_REPLACE:
        case OP_EDITOP_CREATE:
            name_val = val_find_child (newval->parent->parent->parent, "openconfig-platform", "name");
            en_val = newval; //val_find_child (newval, y_openconfig_platform_transceiver_M_openconfig_platform_transceiver, "enabled");
            if (name_val && en_val)
              res = smi_nsm_transceiver_enable_api_auto (azg, VAL_STR(name_val), VAL_BOOL(en_val));
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
             break;
        }
        break;

    default:
        res = NO_ERR;
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;


}

/********************************************************************
* FUNCTION y_openconfig_platform_transceiver_init
* 
* initialize the openconfig-platform-transceiver server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
status_t y_openconfig_platform_transceiver_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;
    agt_profile_t *agt_profile = agt_get_profile();

    y_openconfig_platform_transceiver_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_openconfig_platform_transceiver_M_openconfig_platform_transceiver)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_openconfig_platform_transceiver_R_openconfig_platform_transceiver)) {
        return ERR_NCX_WRONG_VERSION;
    }
    res = ncxmod_load_module(
        y_openconfig_platform_transceiver_M_openconfig_platform_transceiver,
        y_openconfig_platform_transceiver_R_openconfig_platform_transceiver,
        &agt_profile->agt_savedevQ,
        &openconfig_platform_transceiver_mod);
    if (res != NO_ERR) {
        return res;
    }

    transceiver_obj = ncx_find_object(
                            openconfig_platform_transceiver_mod,
        y_openconfig_platform_transceiver_N_transceiver);
    if (openconfig_platform_transceiver_mod == NULL) {
        return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
    }

    res = agt_cb_register_callback(
        y_openconfig_platform_transceiver_M_openconfig_platform_transceiver,
        (const xmlChar *)"/components/component/transceiver/config",
       y_openconfig_platform_transceiver_R_openconfig_platform_transceiver,
        openconfig_platform_transceiver_config_edit);
    if (res != NO_ERR) {
        return res;
    }

    /* put your module initialization code here */
    
    return res;
} /* y_openconfig_platform_transceiver_init */

/********************************************************************
* FUNCTION y_openconfig_platform_transceiver_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
status_t y_openconfig_platform_transceiver_init2 (void)
{
    status_t res = NO_ERR;

    /* put your init2 code here */

    return res;
} /* y_openconfig_platform_transceiver_init2 */

/********************************************************************
* FUNCTION y_openconfig_platform_transceiver_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
void y_openconfig_platform_transceiver_cleanup (void)
{
    /* put your cleanup code here */
    
} /* y_openconfig_platform_transceiver_cleanup */

/* END openconfig_platform_transceiver.c */
